# Generated by Django 3.2.6 on 2021-08-27 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anniversaryfl', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnniversaryFlowers',
        ),
    ]
