# Generated by Django 3.2.6 on 2021-08-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeflowers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecorPlants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views_count', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='homeflowers')),
                ('sale', models.IntegerField(blank=True, default=0, null=True, verbose_name='Discount percentage')),
            ],
            options={
                'verbose_name': 'Декоративное растение',
                'verbose_name_plural': 'Декоративные растения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FlowersinPots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views_count', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='homeflowers')),
                ('sale', models.IntegerField(blank=True, default=0, null=True, verbose_name='Discount percentage')),
            ],
            options={
                'verbose_name': 'Цветы в горшках',
                'verbose_name_plural': 'Цветы в горшках',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HomePlants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views_count', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='homeflowers')),
                ('sale', models.IntegerField(blank=True, default=0, null=True, verbose_name='Discount percentage')),
            ],
            options={
                'verbose_name': 'Комнатное растение',
                'verbose_name_plural': 'Комнатные растения',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='HomeFlowers',
        ),
    ]
