# Generated by Django 3.2.6 on 2021-08-13 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OtherBouquets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Другой вид цветов',
                'verbose_name_plural': 'Другие виды цветов',
            },
        ),
        migrations.CreateModel(
            name='RosesBouquets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views_count', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='flowertypes')),
            ],
            options={
                'verbose_name': 'Букет из роз',
                'verbose_name_plural': 'Букеты из роз',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OtherFlowers',
            fields=[
                ('otherbouquets_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flowertypes.otherbouquets')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views_count', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='flowertypes')),
            ],
            options={
                'verbose_name': 'Другой букет',
                'verbose_name_plural': 'Другие букеты',
                'ordering': ['name'],
            },
            bases=('flowertypes.otherbouquets',),
        ),
    ]
