# Generated by Django 3.2.6 on 2021-08-20 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowertypes', '0002_seasonflowers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OtherFlowers',
        ),
    ]
