# Generated by Django 3.2.6 on 2021-08-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowertypes', '0003_rosesbouquets'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flowersbouquets',
            options={'ordering': ['name'], 'verbose_name': 'Цветы и букеты', 'verbose_name_plural': 'Цветы и букеты'},
        ),
        migrations.AlterModelOptions(
            name='rosesbouquets',
            options={'ordering': ['name'], 'verbose_name': 'Букеты из роз', 'verbose_name_plural': 'Букеты из роз'},
        ),
        migrations.RemoveField(
            model_name='flowersbouquets',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='flowersbouquets',
            name='description',
        ),
        migrations.RemoveField(
            model_name='flowersbouquets',
            name='image',
        ),
        migrations.RemoveField(
            model_name='flowersbouquets',
            name='price',
        ),
        migrations.RemoveField(
            model_name='flowersbouquets',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='flowersbouquets',
            name='views_count',
        ),
        migrations.AlterField(
            model_name='rosesbouquets',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='roses'),
        ),
    ]
