# Generated by Django 3.2.6 on 2021-08-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowertypes', '0003_auto_20210820_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='assortedflowers',
            name='discount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Discount percentage'),
        ),
    ]
