# Generated by Django 3.2.6 on 2021-08-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowertypes', '0005_rename_discount_assortedflowers_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='rosesbouquets',
            name='sale',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Discount percentage'),
        ),
        migrations.AddField(
            model_name='seasonflowers',
            name='sale',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Discount percentage'),
        ),
    ]
