# Generated by Django 3.2.6 on 2021-08-22 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_delete_sale'),
        ('flowertypes', '0007_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
